[package]
name = "bn128-over-m31"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.4.2"
ark-ec = "0.4.2"
ark-std = "0.4.0"
num-bigint = "0.4"
serde = { version = "1.0", features = ["derive"] }
hex = "0.4"
